// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace GUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        #region Properties
        public UIMagicMemoWindow UIMagicMemoWindow
        {
            get
            {
                if ((this.mUIMagicMemoWindow == null))
                {
                    this.mUIMagicMemoWindow = new UIMagicMemoWindow();
                }
                return this.mUIMagicMemoWindow;
            }
        }
        
        public UIMagicMemoWindow1 UIMagicMemoWindow1
        {
            get
            {
                if ((this.mUIMagicMemoWindow1 == null))
                {
                    this.mUIMagicMemoWindow1 = new UIMagicMemoWindow1();
                }
                return this.mUIMagicMemoWindow1;
            }
        }
        
        public UIMicrosoftVisualCRuntWindow UIMicrosoftVisualCRuntWindow
        {
            get
            {
                if ((this.mUIMicrosoftVisualCRuntWindow == null))
                {
                    this.mUIMicrosoftVisualCRuntWindow = new UIMicrosoftVisualCRuntWindow();
                }
                return this.mUIMicrosoftVisualCRuntWindow;
            }
        }
        
        public UIMainControllerTestcpWindow UIMainControllerTestcpWindow
        {
            get
            {
                if ((this.mUIMainControllerTestcpWindow == null))
                {
                    this.mUIMainControllerTestcpWindow = new UIMainControllerTestcpWindow();
                }
                return this.mUIMainControllerTestcpWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMagicMemoWindow mUIMagicMemoWindow;
        
        private UIMagicMemoWindow1 mUIMagicMemoWindow1;
        
        private UIMicrosoftVisualCRuntWindow mUIMicrosoftVisualCRuntWindow;
        
        private UIMainControllerTestcpWindow mUIMainControllerTestcpWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMagicMemoWindow : WinWindow
    {
        
        public UIMagicMemoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Magic Memo";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public UICommandInputBoxWindow UICommandInputBoxWindow
        {
            get
            {
                if ((this.mUICommandInputBoxWindow == null))
                {
                    this.mUICommandInputBoxWindow = new UICommandInputBoxWindow(this);
                }
                return this.mUICommandInputBoxWindow;
            }
        }
        
        public UIAllTaskBoxWindow UIAllTaskBoxWindow
        {
            get
            {
                if ((this.mUIAllTaskBoxWindow == null))
                {
                    this.mUIAllTaskBoxWindow = new UIAllTaskBoxWindow(this);
                }
                return this.mUIAllTaskBoxWindow;
            }
        }
        
        public UICommandInputBoxWindow1 UICommandInputBoxWindow1
        {
            get
            {
                if ((this.mUICommandInputBoxWindow1 == null))
                {
                    this.mUICommandInputBoxWindow1 = new UICommandInputBoxWindow1(this);
                }
                return this.mUICommandInputBoxWindow1;
            }
        }
        
        public UICommandInputBoxWindow2 UICommandInputBoxWindow2
        {
            get
            {
                if ((this.mUICommandInputBoxWindow2 == null))
                {
                    this.mUICommandInputBoxWindow2 = new UICommandInputBoxWindow2(this);
                }
                return this.mUICommandInputBoxWindow2;
            }
        }
        
        public UICommandInputBoxWindow3 UICommandInputBoxWindow3
        {
            get
            {
                if ((this.mUICommandInputBoxWindow3 == null))
                {
                    this.mUICommandInputBoxWindow3 = new UICommandInputBoxWindow3(this);
                }
                return this.mUICommandInputBoxWindow3;
            }
        }
        
        public UICommandInputBoxWindow4 UICommandInputBoxWindow4
        {
            get
            {
                if ((this.mUICommandInputBoxWindow4 == null))
                {
                    this.mUICommandInputBoxWindow4 = new UICommandInputBoxWindow4(this);
                }
                return this.mUICommandInputBoxWindow4;
            }
        }
        
        public UICommandInputBoxWindow5 UICommandInputBoxWindow5
        {
            get
            {
                if ((this.mUICommandInputBoxWindow5 == null))
                {
                    this.mUICommandInputBoxWindow5 = new UICommandInputBoxWindow5(this);
                }
                return this.mUICommandInputBoxWindow5;
            }
        }
        
        public UICommandInputBoxWindow6 UICommandInputBoxWindow6
        {
            get
            {
                if ((this.mUICommandInputBoxWindow6 == null))
                {
                    this.mUICommandInputBoxWindow6 = new UICommandInputBoxWindow6(this);
                }
                return this.mUICommandInputBoxWindow6;
            }
        }
        
        public UICommandInputBoxWindow7 UICommandInputBoxWindow7
        {
            get
            {
                if ((this.mUICommandInputBoxWindow7 == null))
                {
                    this.mUICommandInputBoxWindow7 = new UICommandInputBoxWindow7(this);
                }
                return this.mUICommandInputBoxWindow7;
            }
        }
        
        public UICommandInputBoxWindow8 UICommandInputBoxWindow8
        {
            get
            {
                if ((this.mUICommandInputBoxWindow8 == null))
                {
                    this.mUICommandInputBoxWindow8 = new UICommandInputBoxWindow8(this);
                }
                return this.mUICommandInputBoxWindow8;
            }
        }
        
        public UICommandInputBoxWindow9 UICommandInputBoxWindow9
        {
            get
            {
                if ((this.mUICommandInputBoxWindow9 == null))
                {
                    this.mUICommandInputBoxWindow9 = new UICommandInputBoxWindow9(this);
                }
                return this.mUICommandInputBoxWindow9;
            }
        }
        
        public UICommandInputBoxWindow10 UICommandInputBoxWindow10
        {
            get
            {
                if ((this.mUICommandInputBoxWindow10 == null))
                {
                    this.mUICommandInputBoxWindow10 = new UICommandInputBoxWindow10(this);
                }
                return this.mUICommandInputBoxWindow10;
            }
        }
        
        public UICommandInputBoxWindow11 UICommandInputBoxWindow11
        {
            get
            {
                if ((this.mUICommandInputBoxWindow11 == null))
                {
                    this.mUICommandInputBoxWindow11 = new UICommandInputBoxWindow11(this);
                }
                return this.mUICommandInputBoxWindow11;
            }
        }
        
        public UICommandInputBoxWindow12 UICommandInputBoxWindow12
        {
            get
            {
                if ((this.mUICommandInputBoxWindow12 == null))
                {
                    this.mUICommandInputBoxWindow12 = new UICommandInputBoxWindow12(this);
                }
                return this.mUICommandInputBoxWindow12;
            }
        }
        
        public UIDeletedlinenumbers12Window UIDeletedlinenumbers12Window
        {
            get
            {
                if ((this.mUIDeletedlinenumbers12Window == null))
                {
                    this.mUIDeletedlinenumbers12Window = new UIDeletedlinenumbers12Window(this);
                }
                return this.mUIDeletedlinenumbers12Window;
            }
        }
        
        public UITodayTaskBoxWindow UITodayTaskBoxWindow
        {
            get
            {
                if ((this.mUITodayTaskBoxWindow == null))
                {
                    this.mUITodayTaskBoxWindow = new UITodayTaskBoxWindow(this);
                }
                return this.mUITodayTaskBoxWindow;
            }
        }
        
        public UIMagicMemoClient UIMagicMemoClient
        {
            get
            {
                if ((this.mUIMagicMemoClient == null))
                {
                    this.mUIMagicMemoClient = new UIMagicMemoClient(this);
                }
                return this.mUIMagicMemoClient;
            }
        }
        
        public UICommandInputBoxWindow13 UICommandInputBoxWindow13
        {
            get
            {
                if ((this.mUICommandInputBoxWindow13 == null))
                {
                    this.mUICommandInputBoxWindow13 = new UICommandInputBoxWindow13(this);
                }
                return this.mUICommandInputBoxWindow13;
            }
        }
        
        public UICommandInputBoxWindow14 UICommandInputBoxWindow14
        {
            get
            {
                if ((this.mUICommandInputBoxWindow14 == null))
                {
                    this.mUICommandInputBoxWindow14 = new UICommandInputBoxWindow14(this);
                }
                return this.mUICommandInputBoxWindow14;
            }
        }
        
        public UICommandInputBoxWindow15 UICommandInputBoxWindow15
        {
            get
            {
                if ((this.mUICommandInputBoxWindow15 == null))
                {
                    this.mUICommandInputBoxWindow15 = new UICommandInputBoxWindow15(this);
                }
                return this.mUICommandInputBoxWindow15;
            }
        }
        
        public UICommandInputBoxWindow16 UICommandInputBoxWindow16
        {
            get
            {
                if ((this.mUICommandInputBoxWindow16 == null))
                {
                    this.mUICommandInputBoxWindow16 = new UICommandInputBoxWindow16(this);
                }
                return this.mUICommandInputBoxWindow16;
            }
        }
        
        public UICommandInputBoxWindow17 UICommandInputBoxWindow17
        {
            get
            {
                if ((this.mUICommandInputBoxWindow17 == null))
                {
                    this.mUICommandInputBoxWindow17 = new UICommandInputBoxWindow17(this);
                }
                return this.mUICommandInputBoxWindow17;
            }
        }
        
        public UICommandInputBoxWindow18 UICommandInputBoxWindow18
        {
            get
            {
                if ((this.mUICommandInputBoxWindow18 == null))
                {
                    this.mUICommandInputBoxWindow18 = new UICommandInputBoxWindow18(this);
                }
                return this.mUICommandInputBoxWindow18;
            }
        }
        
        public UICommandInputBoxWindow19 UICommandInputBoxWindow19
        {
            get
            {
                if ((this.mUICommandInputBoxWindow19 == null))
                {
                    this.mUICommandInputBoxWindow19 = new UICommandInputBoxWindow19(this);
                }
                return this.mUICommandInputBoxWindow19;
            }
        }
        #endregion
        
        #region Fields
        private UICommandInputBoxWindow mUICommandInputBoxWindow;
        
        private UIAllTaskBoxWindow mUIAllTaskBoxWindow;
        
        private UICommandInputBoxWindow1 mUICommandInputBoxWindow1;
        
        private UICommandInputBoxWindow2 mUICommandInputBoxWindow2;
        
        private UICommandInputBoxWindow3 mUICommandInputBoxWindow3;
        
        private UICommandInputBoxWindow4 mUICommandInputBoxWindow4;
        
        private UICommandInputBoxWindow5 mUICommandInputBoxWindow5;
        
        private UICommandInputBoxWindow6 mUICommandInputBoxWindow6;
        
        private UICommandInputBoxWindow7 mUICommandInputBoxWindow7;
        
        private UICommandInputBoxWindow8 mUICommandInputBoxWindow8;
        
        private UICommandInputBoxWindow9 mUICommandInputBoxWindow9;
        
        private UICommandInputBoxWindow10 mUICommandInputBoxWindow10;
        
        private UICommandInputBoxWindow11 mUICommandInputBoxWindow11;
        
        private UICommandInputBoxWindow12 mUICommandInputBoxWindow12;
        
        private UIDeletedlinenumbers12Window mUIDeletedlinenumbers12Window;
        
        private UITodayTaskBoxWindow mUITodayTaskBoxWindow;
        
        private UIMagicMemoClient mUIMagicMemoClient;
        
        private UICommandInputBoxWindow13 mUICommandInputBoxWindow13;
        
        private UICommandInputBoxWindow14 mUICommandInputBoxWindow14;
        
        private UICommandInputBoxWindow15 mUICommandInputBoxWindow15;
        
        private UICommandInputBoxWindow16 mUICommandInputBoxWindow16;
        
        private UICommandInputBoxWindow17 mUICommandInputBoxWindow17;
        
        private UICommandInputBoxWindow18 mUICommandInputBoxWindow18;
        
        private UICommandInputBoxWindow19 mUICommandInputBoxWindow19;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow : WinWindow
    {
        
        public UICommandInputBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAllTaskBoxWindow : WinWindow
    {
        
        public UIAllTaskBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "allTaskBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAllTaskBoxEdit
        {
            get
            {
                if ((this.mUIAllTaskBoxEdit == null))
                {
                    this.mUIAllTaskBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAllTaskBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Magic Memo";
                    this.mUIAllTaskBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUIAllTaskBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAllTaskBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow1 : WinWindow
    {
        
        public UICommandInputBoxWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow2 : WinWindow
    {
        
        public UICommandInputBoxWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow3 : WinWindow
    {
        
        public UICommandInputBoxWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow4 : WinWindow
    {
        
        public UICommandInputBoxWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow5 : WinWindow
    {
        
        public UICommandInputBoxWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow6 : WinWindow
    {
        
        public UICommandInputBoxWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow7 : WinWindow
    {
        
        public UICommandInputBoxWindow7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow8 : WinWindow
    {
        
        public UICommandInputBoxWindow8(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow9 : WinWindow
    {
        
        public UICommandInputBoxWindow9(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow10 : WinWindow
    {
        
        public UICommandInputBoxWindow10(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow11 : WinWindow
    {
        
        public UICommandInputBoxWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow12 : WinWindow
    {
        
        public UICommandInputBoxWindow12(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIDeletedlinenumbers12Window : WinWindow
    {
        
        public UIDeletedlinenumbers12Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "successMessageLabel";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinText UIDeletedlinenumbers12Text
        {
            get
            {
                if ((this.mUIDeletedlinenumbers12Text == null))
                {
                    this.mUIDeletedlinenumbers12Text = new WinText(this);
                    #region Search Criteria
                    this.mUIDeletedlinenumbers12Text.SearchProperties[WinText.PropertyNames.Name] = "Deleted line numbers: 1, 2, Invalid line number specified: 3, 4, 5, 6";
                    this.mUIDeletedlinenumbers12Text.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUIDeletedlinenumbers12Text;
            }
        }
        
        public WinText UISearchresultsforaText
        {
            get
            {
                if ((this.mUISearchresultsforaText == null))
                {
                    this.mUISearchresultsforaText = new WinText(this);
                    #region Search Criteria
                    this.mUISearchresultsforaText.SearchProperties[WinText.PropertyNames.Name] = "Search results for: \"a\" ";
                    this.mUISearchresultsforaText.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUISearchresultsforaText;
            }
        }
        
        public WinText UINotificationtimechanText
        {
            get
            {
                if ((this.mUINotificationtimechanText == null))
                {
                    this.mUINotificationtimechanText = new WinText(this);
                    #region Search Criteria
                    this.mUINotificationtimechanText.SearchProperties[WinText.PropertyNames.Name] = "Notification time changed from 1 minute(s) to 1 minute(s)";
                    this.mUINotificationtimechanText.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUINotificationtimechanText;
            }
        }
        
        public WinText UIInvalidnumberspecifiText
        {
            get
            {
                if ((this.mUIInvalidnumberspecifiText == null))
                {
                    this.mUIInvalidnumberspecifiText = new WinText(this);
                    #region Search Criteria
                    this.mUIInvalidnumberspecifiText.SearchProperties[WinText.PropertyNames.Name] = "Invalid number specified!";
                    this.mUIInvalidnumberspecifiText.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUIInvalidnumberspecifiText;
            }
        }
        
        public WinText UIInvalidnumberspecifiText1
        {
            get
            {
                if ((this.mUIInvalidnumberspecifiText1 == null))
                {
                    this.mUIInvalidnumberspecifiText1 = new WinText(this);
                    #region Search Criteria
                    this.mUIInvalidnumberspecifiText1.SearchProperties[WinText.PropertyNames.Name] = "Invalid number specified!";
                    this.mUIInvalidnumberspecifiText1.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUIInvalidnumberspecifiText1;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIDeletedlinenumbers12Text;
        
        private WinText mUISearchresultsforaText;
        
        private WinText mUINotificationtimechanText;
        
        private WinText mUIInvalidnumberspecifiText;
        
        private WinText mUIInvalidnumberspecifiText1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITodayTaskBoxWindow : WinWindow
    {
        
        public UITodayTaskBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "todayTaskBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UITodayTaskBoxEdit
        {
            get
            {
                if ((this.mUITodayTaskBoxEdit == null))
                {
                    this.mUITodayTaskBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITodayTaskBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUITodayTaskBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITodayTaskBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMagicMemoClient : WinClient
    {
        
        public UIMagicMemoClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Magic Memo";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinWindow UIPictureBoxWindow
        {
            get
            {
                if ((this.mUIPictureBoxWindow == null))
                {
                    this.mUIPictureBoxWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIPictureBoxWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Added line: \"task4\"";
                    this.mUIPictureBoxWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
                    this.mUIPictureBoxWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
                    this.mUIPictureBoxWindow.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUIPictureBoxWindow;
            }
        }
        
        public WinWindow UICommandInputBoxWindow
        {
            get
            {
                if ((this.mUICommandInputBoxWindow == null))
                {
                    this.mUICommandInputBoxWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUICommandInputBoxWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Upcoming Tasks";
                    this.mUICommandInputBoxWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUICommandInputBoxWindow.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIPictureBoxWindow;
        
        private WinWindow mUICommandInputBoxWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow13 : WinWindow
    {
        
        public UICommandInputBoxWindow13(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow14 : WinWindow
    {
        
        public UICommandInputBoxWindow14(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow15 : WinWindow
    {
        
        public UICommandInputBoxWindow15(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow16 : WinWindow
    {
        
        public UICommandInputBoxWindow16(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow17 : WinWindow
    {
        
        public UICommandInputBoxWindow17(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow18 : WinWindow
    {
        
        public UICommandInputBoxWindow18(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICommandInputBoxWindow19 : WinWindow
    {
        
        public UICommandInputBoxWindow19(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "commandInputBox";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinEdit UICommandInputBoxEdit
        {
            get
            {
                if ((this.mUICommandInputBoxEdit == null))
                {
                    this.mUICommandInputBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICommandInputBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Upcoming Tasks";
                    this.mUICommandInputBoxEdit.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUICommandInputBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICommandInputBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMagicMemoWindow1 : WinWindow
    {
        
        public UIMagicMemoWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Magic Memo";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.FilterProperties[WinWindow.PropertyNames.OrderOfInvocation] = "2";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public UIMagicMemoClient1 UIMagicMemoClient
        {
            get
            {
                if ((this.mUIMagicMemoClient == null))
                {
                    this.mUIMagicMemoClient = new UIMagicMemoClient1(this);
                }
                return this.mUIMagicMemoClient;
            }
        }
        #endregion
        
        #region Fields
        private UIMagicMemoClient1 mUIMagicMemoClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMagicMemoClient1 : WinClient
    {
        
        public UIMagicMemoClient1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Magic Memo";
            this.WindowTitles.Add("Magic Memo");
            #endregion
        }
        
        #region Properties
        public WinButton UIQuitButton
        {
            get
            {
                if ((this.mUIQuitButton == null))
                {
                    this.mUIQuitButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIQuitButton.SearchProperties[WinButton.PropertyNames.Name] = "Quit";
                    this.mUIQuitButton.WindowTitles.Add("Magic Memo");
                    #endregion
                }
                return this.mUIQuitButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIQuitButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMicrosoftVisualCRuntWindow : WinWindow
    {
        
        public UIMicrosoftVisualCRuntWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Microsoft Visual C++ Runtime Library";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Microsoft Visual C++ Runtime Library");
            #endregion
        }
        
        #region Properties
        public UI重试RWindow UI重试RWindow
        {
            get
            {
                if ((this.mUI重试RWindow == null))
                {
                    this.mUI重试RWindow = new UI重试RWindow(this);
                }
                return this.mUI重试RWindow;
            }
        }
        #endregion
        
        #region Fields
        private UI重试RWindow mUI重试RWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UI重试RWindow : WinWindow
    {
        
        public UI重试RWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "4";
            this.WindowTitles.Add("Microsoft Visual C++ Runtime Library");
            #endregion
        }
        
        #region Properties
        public WinButton UI重试RButton
        {
            get
            {
                if ((this.mUI重试RButton == null))
                {
                    this.mUI重试RButton = new WinButton(this);
                    #region Search Criteria
                    this.mUI重试RButton.SearchProperties[WinButton.PropertyNames.Name] = "重试(R)";
                    this.mUI重试RButton.WindowTitles.Add("Microsoft Visual C++ Runtime Library");
                    #endregion
                }
                return this.mUI重试RButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUI重试RButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMainControllerTestcpWindow : WinWindow
    {
        
        public UIMainControllerTestcpWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "main/ControllerTest.cpp at master · cs2103jan2015-w11-2c/main - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("main/ControllerTest.cpp at master · cs2103jan2015-w11-2c/main - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "271532200";
            this.WindowTitles.Add("main/ControllerTest.cpp at master · cs2103jan2015-w11-2c/main - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIMainControllerTestcpDocument
        {
            get
            {
                if ((this.mUIMainControllerTestcpDocument == null))
                {
                    this.mUIMainControllerTestcpDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIMainControllerTestcpDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIMainControllerTestcpDocument.WindowTitles.Add("main/ControllerTest.cpp at master · cs2103jan2015-w11-2c/main - Google Chrome");
                    #endregion
                }
                return this.mUIMainControllerTestcpDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIMainControllerTestcpDocument;
        #endregion
    }
}
